assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml

release:
  script:
    - "rm -rf *.gem"
    - "gem build jgd.gemspec"
    - "chmod 0600 ../rubygems.yml"
    - "gem push *.gem --key ../rubygems.yml"

