language: ruby
branches:
  only:
    - master
install:
  - bundle install
script:
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test"
  - rake
  - ./test.sh

